import { v4 as uuid } from 'uuid';
import type { IntentPayloadInput } from '@hari/core';

// ─────────────────────────────────────────────────────────────────────────────
// Workflow scenario: "New service onboarding wizard"
//
// Demonstrates the workflow intent type with a 5-step guided process for
// registering a new microservice in the platform: service metadata,
// infrastructure config, observability settings, access control, and a
// final review/confirmation step.
// ─────────────────────────────────────────────────────────────────────────────

export const workflowOnboardingIntent: IntentPayloadInput = {
  version: '1.0.0',
  intentId: uuid(),
  type: 'workflow',
  domain: 'onboarding',
  primaryGoal: 'Guide the engineer through registering a new microservice on the platform',
  confidence: 0.99,
  density: 'operator',
  layoutHint: 'form',

  data: {
    title: 'New Service Onboarding',
    currentStepIndex: 1,
    allowSkipAhead: false,
    finishLabel: 'Register Service',
    steps: [
      {
        id: 'service-meta',
        title: 'Service Details',
        description: 'Basic identity and ownership information for the new service.',
        status: 'completed',
        type: 'form',
        icon: '📋',
        skippable: false,
        fields: [
          {
            id: 'service_name',
            label: 'Service Name',
            type: 'text',
            required: true,
            disabled: false,
            sensitive: false,
            validation: [
              { rule: 'minLength', value: 3, message: 'Must be at least 3 characters' },
              { rule: 'pattern', value: '^[a-z][a-z0-9-]+$', message: 'Lowercase letters, numbers and hyphens only; must start with a letter' },
            ],
            multiline: false,
            placeholder: 'e.g. payment-processor',
            helpText: 'Used as the Kubernetes service name and DNS label.',
          },
          {
            id: 'owner_team',
            label: 'Owning Team',
            type: 'select',
            required: true,
            disabled: false,
            sensitive: false,
            validation: [],
            multiple: false,
            searchable: false,
            options: [
              { value: 'platform', label: 'Platform Engineering' },
              { value: 'product', label: 'Product Engineering' },
              { value: 'ai-ml', label: 'AI / ML' },
              { value: 'qa', label: 'Quality Engineering' },
            ],
          },
          {
            id: 'description',
            label: 'Description',
            type: 'textarea',
            required: false,
            disabled: false,
            sensitive: false,
            validation: [],
            multiline: true,
            placeholder: 'What does this service do?',
          },
          {
            id: 'tier',
            label: 'Service Tier',
            type: 'radio',
            required: true,
            disabled: false,
            sensitive: false,
            validation: [],
            options: [
              { value: 'tier-1', label: 'Tier 1 — customer-critical (SLA 99.99%)' },
              { value: 'tier-2', label: 'Tier 2 — business-critical (SLA 99.9%)' },
              { value: 'tier-3', label: 'Tier 3 — internal / best-effort' },
            ],
          },
        ],
      },
      {
        id: 'infra-config',
        title: 'Infrastructure',
        description: 'Runtime environment, compute resources, and scaling policy.',
        status: 'in_progress',
        type: 'form',
        icon: '🖥',
        skippable: false,
        fields: [
          {
            id: 'runtime',
            label: 'Runtime',
            type: 'select',
            required: true,
            disabled: false,
            sensitive: false,
            validation: [],
            multiple: false,
            searchable: false,
            options: [
              { value: 'node20', label: 'Node.js 20 LTS' },
              { value: 'python312', label: 'Python 3.12' },
              { value: 'go122', label: 'Go 1.22' },
              { value: 'jvm21', label: 'JVM 21 (Java / Kotlin)' },
            ],
          },
          {
            id: 'cpu_request',
            label: 'CPU Request (millicores)',
            type: 'number',
            required: true,
            disabled: false,
            sensitive: false,
            validation: [
              { rule: 'min', value: 50, message: 'Minimum 50 m' },
              { rule: 'max', value: 4000, message: 'Maximum 4000 m per pod' },
            ],
            placeholder: '250',
            helpText: 'Kubernetes CPU request in millicores (1000 m = 1 vCPU).',
          },
          {
            id: 'memory_request',
            label: 'Memory Request (MiB)',
            type: 'number',
            required: true,
            disabled: false,
            sensitive: false,
            validation: [
              { rule: 'min', value: 64, message: 'Minimum 64 MiB' },
              { rule: 'max', value: 8192, message: 'Maximum 8192 MiB per pod' },
            ],
            placeholder: '512',
          },
          {
            id: 'min_replicas',
            label: 'Min Replicas',
            type: 'number',
            required: true,
            disabled: false,
            sensitive: false,
            validation: [
              { rule: 'min', value: 1, message: 'Must be at least 1' },
            ],
            placeholder: '2',
          },
          {
            id: 'max_replicas',
            label: 'Max Replicas',
            type: 'number',
            required: true,
            disabled: false,
            sensitive: false,
            validation: [
              { rule: 'min', value: 1, message: 'Must be at least 1' },
            ],
            placeholder: '10',
          },
          {
            id: 'multi_region',
            label: 'Deploy to multiple regions',
            type: 'checkbox',
            required: false,
            disabled: false,
            sensitive: false,
            validation: [],
            helpText: 'US-EAST and EU-WEST will both be provisioned.',
          },
        ],
      },
      {
        id: 'observability',
        title: 'Observability',
        description: 'Configure metrics, logging, alerting, and on-call assignment.',
        status: 'pending',
        type: 'form',
        icon: '📊',
        skippable: false,
        fields: [
          {
            id: 'log_level',
            label: 'Default Log Level',
            type: 'select',
            required: true,
            disabled: false,
            sensitive: false,
            validation: [],
            multiple: false,
            searchable: false,
            options: [
              { value: 'error', label: 'ERROR' },
              { value: 'warn',  label: 'WARN' },
              { value: 'info',  label: 'INFO' },
              { value: 'debug', label: 'DEBUG' },
            ],
          },
          {
            id: 'enable_tracing',
            label: 'Enable distributed tracing (OpenTelemetry)',
            type: 'checkbox',
            required: false,
            disabled: false,
            sensitive: false,
            validation: [],
          },
          {
            id: 'alert_email',
            label: 'Alert Email / PagerDuty key',
            type: 'text',
            required: true,
            disabled: false,
            sensitive: true,
            validation: [
              { rule: 'pattern', value: '^[^@]+@[^@]+\\.[^@]+$|^[A-Za-z0-9+/]{32,}$', message: 'Enter a valid email address or PagerDuty routing key' },
            ],
            multiline: false,
            placeholder: 'oncall@example.com',
          },
          {
            id: 'error_budget_pct',
            label: 'Error Budget (%)',
            type: 'number',
            required: false,
            disabled: false,
            sensitive: false,
            validation: [
              { rule: 'min', value: 0.001, message: 'Must be greater than 0' },
              { rule: 'max', value: 10, message: 'Must be 10% or less' },
            ],
            placeholder: '0.1',
            helpText: 'Monthly error budget derived from the chosen SLA tier.',
          },
        ],
      },
      {
        id: 'access-control',
        title: 'Access & Secrets',
        description: 'IAM roles, secret injection, and inter-service authorisation.',
        status: 'pending',
        type: 'form',
        icon: '🔒',
        skippable: true,
        fields: [
          {
            id: 'iam_role',
            label: 'IAM Role ARN (optional)',
            type: 'text',
            required: false,
            disabled: false,
            sensitive: false,
            validation: [
              { rule: 'pattern', value: '^arn:aws:iam::\\d{12}:role/.+|^$', message: 'Must be a valid IAM role ARN or left blank' },
            ],
            multiline: false,
            placeholder: 'arn:aws:iam::123456789012:role/my-service-role',
          },
          {
            id: 'secrets',
            label: 'Secret Keys to Inject',
            type: 'text',
            required: false,
            disabled: false,
            sensitive: false,
            validation: [],
            multiline: false,
            placeholder: 'DB_PASSWORD, API_SECRET_KEY',
            helpText: 'Comma-separated keys from Vault. Values are never stored here.',
          },
          {
            id: 'allow_public',
            label: 'Expose public HTTP endpoint',
            type: 'checkbox',
            required: false,
            disabled: false,
            sensitive: false,
            validation: [],
            helpText: 'Creates an ingress rule and TLS cert via cert-manager.',
          },
        ],
      },
      {
        id: 'review',
        title: 'Review & Register',
        description: 'Confirm the settings below before creating the service.',
        status: 'pending',
        type: 'review',
        icon: '✅',
        skippable: false,
        reviewItems: [
          { label: 'Service Name', value: '(from Step 1)', highlight: true },
          { label: 'Owning Team', value: '(from Step 1)', highlight: false },
          { label: 'Tier', value: '(from Step 1)', highlight: true },
          { label: 'Runtime', value: '(from Step 2)', highlight: false },
          { label: 'CPU / Memory', value: '(from Step 2)', highlight: false },
          { label: 'Replicas', value: 'min 2 → max 10', highlight: false },
          { label: 'Log Level', value: '(from Step 3)', highlight: false },
          { label: 'Tracing', value: '(from Step 3)', highlight: false },
          { label: 'Public endpoint', value: '(from Step 4)', highlight: true },
        ],
      },
    ],
  },

  explainability: {
    title: 'Why is this wizard shown?',
    summary: 'You requested to register a new microservice. The agent launched the standard platform onboarding workflow, which ensures all required infrastructure and compliance settings are captured before provisioning begins.',
    confidence: 0.99,
    elements: {},
  },
};
